### ISSUE TITLE
Incomplete display

### ISSUE THREAD

**Issue by j2501987804** [V2BlockBuster2K/Awespuccin#1]
The icon is not fully displayed.
I can't see the details in the message notice, I don't know what's wrong, and it's unlimited.

env：
os：arch
Resolution：4k
dpi：144

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/41771911/197562907-54f125f4-d7c4-4839-a5aa-7a8b3933e3e4.png">

**Comment by V2BlockBuster2K** [comment]
This issue with the Font comes bc you installed the font from the repo not from the Folder, I also had the problem with the FiraCode Nerd font from the AUR but from the folder the icons should get displayed correctly. Have you set up the Variables? 
If you want to see the Error, I just added scroll box support so just copy the [new file](https://github.com/V2BlockBuster2K/Awespuccin/blob/main/conf/awesome/ui/notif-panel/init.lua) "Awespuccin/conf/awesome/ui/notif-panel/init.lua" to "~/.config/awesome/ui/notif-panel/init.lua" (replace the old init.lua with the new one) then you should see the full error if you open the notif panel!

**Comment by j2501987804** [comment]
@V2BlockBuster2K 
The icon problem is ok, it seems that there is something wrong with the memory module.

https://github.com/V2BlockBuster2K/Awespuccin/issues/1#issuecomment-1289214124

**Comment by j2501987804** [comment]
@V2BlockBuster2K 
Thanks! The icon problem is ok, it seems that there is something wrong with the memory module.

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/41771911/197576463-b36bd73b-b7f3-4f9d-8d89-4550cfe76fc8.png">

**Comment by V2BlockBuster2K** [comment]
Ok can you test the script of the ~/.config/awesome/signals/mem.lua (**free | grep Mem | awk '{print $3/$2 * 100.0}' | cut -f 1 -d "."**) and say if it works ? Because on my machine, and also on a VM it's working fine. (idk if you know lua, bc the error means there is no value behind the mem_perc but it should have given the value if the above mentioned script works on your machine)
