### ISSUE TITLE
How to check the full content of a notification?

### ISSUE THREAD

**Issue by ywpkwon** [V2BlockBuster2K/Awespuccin#2]
When a notification message is long, the notification center doesn't show its full message. The mouse left click removes the message. Is there a way to check the full message?

![Screenshot-2022-10-29T23:27:40-07:00](https://user-images.githubusercontent.com/18429284/198865663-9b7e8343-c397-429b-84dd-e09fe08f9e0d.png)

**Comment by V2BlockBuster2K** [comment]
Do you have the newest version of the Repo (updatet 6 days ago), bc in the update I added that the message should slowly scroll that you can see the whole thing! [here](https://github.com/V2BlockBuster2K/Awespuccin/blob/main/conf/awesome/ui/notif-panel/init.lua)

Like this:

https://user-images.githubusercontent.com/84659429/198865926-2ce7bccb-d704-428e-a1f6-c6e0e1389156.mp4

**Comment by ywpkwon** [comment]
I checked it works. Thanks. You are awesome :)
